from django.urls import path
from .views import (
    dashboard_view,
    documentation_view,
    login_view,
    signup_view,
    logout_view,
    password_reset_view,
    password_reset_confirm_view,
    StoriesView,
    StoryDetailView,
    WeatherDataPMDFFDView,
    GdacsEventsGeojsonApi,
    GdacsEventDetailsApi,
    NasaEonetEventsGeojsonApi,
    UsgsEarthquakeAlertsGeojsonApi,
    UsgsEarthquakeDetailApi,
    UsgsShakemapContentProxyApi,
    GeoGlowsRiverIdApi,
    GeoGlowsForecastApi,
    GeoGlowsForecastStatsApi,
    GeoGlowsDailyAveragesApi,
    GeoGlowsMonthlyAveragesApi,
    GeoGlowsAnnualAveragesApi,
    WAQIgeojson,
    DynamicGEELayerView,
    GEECatalogView,
    GenerateLegendView,
    TemporalGEELayerView,
    SlickPlusGeojsonApi,
    GdeltNewsEventsApi,
    WindOceanParticleDataApi,
    HeatwaveMonitoringView,
    HeatwaveDetailView,


)


urlpatterns = [
    path("", dashboard_view, name="dashboard"),
    path("docs/", documentation_view, name="documentation"),

    path("login/", login_view, name="login"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("password-reset/", password_reset_view, name="password_reset"),
    path("password-reset-confirm/<uidb64>/<token>/", password_reset_confirm_view, name="password_reset_confirm"),
    path("stories/", StoriesView.as_view(), name="stories"),
    path("stories/<slug:slug>/", StoryDetailView.as_view(), name="story-detail"),
    path("get-weather-pmdffd-data/", WeatherDataPMDFFDView.as_view(), name="get-weather-pmdffd-data",),
    path("get-waqi-global-airquality/", WAQIgeojson.as_view(), name="waqi_global_aqi"),
    path("api/slick-plus/", SlickPlusGeojsonApi.as_view(), name="slick_plus_geojson"),
    path("get-gdacs-events/<str:event_slug>/",GdacsEventsGeojsonApi.as_view(),name="get-gdacs-events",),
    path("get-gdacs-event-details/<str:event_type>/<int:event_id>/",GdacsEventDetailsApi.as_view(),name="gdacs-event-details",),
    path("get-gdacs-event-details/<str:event_type>/<int:event_id>/<int:episode_id>/",GdacsEventDetailsApi.as_view(),name="gdacs-event-details-ep",),
    path("get-nasa-eonet-events/<str:category_slug>/", NasaEonetEventsGeojsonApi.as_view(), name="nasa-eonet-events"),
    path("get-usgs-earthquake-alerts/", UsgsEarthquakeAlertsGeojsonApi.as_view(), name="usgs-earthquake-alerts"),
    path("get-usgs-earthquake-detail/<str:event_id>/", UsgsEarthquakeDetailApi.as_view(), name="usgs-earthquake-detail"),
    path("get-usgs-shakemap-content/", UsgsShakemapContentProxyApi.as_view(), name="usgs-shakemap-content"),
    path("get-geoglows-riverid/", GeoGlowsRiverIdApi.as_view(), name="geoglows-riverid"),
    path("get-geoglows-forecast/<int:river_id>/", GeoGlowsForecastApi.as_view(), name="geoglows-forecast"),
    path("get-geoglows-forecaststats/<int:river_id>/", GeoGlowsForecastStatsApi.as_view(), name="geoglows-forecaststats"),
    path("get-geoglows-dailyaverages/<int:river_id>/", GeoGlowsDailyAveragesApi.as_view(), name="geoglows-dailyaverages"),
    path("get-geoglows-monthlyaverages/<int:river_id>/", GeoGlowsMonthlyAveragesApi.as_view(), name="geoglows-monthlyaverages"),
    path("get-geoglows-annualaverages/<int:river_id>/", GeoGlowsAnnualAveragesApi.as_view(), name="geoglows-annualaverages"),
    path('api/gee/dynamic-layer/', DynamicGEELayerView.as_view(), name='dynamic_gee'),
    path('api/gee/catalog/', GEECatalogView.as_view(), name='gee_catalog'),
    path('api/gee/legend/', GenerateLegendView.as_view(), name='gee_legend'),
    path('api/gee/temporal-layer/', TemporalGEELayerView.as_view(), name='temporal_gee_layer'),
    path("api/wind-ocean-particles/", WindOceanParticleDataApi.as_view(), name="wind_ocean_particles"),
    path( "get-gdelt-news-events/", GdeltNewsEventsApi.as_view(), name="gdelt-news-events" ),
    path("get-heatwave-monitoring/", HeatwaveMonitoringView.as_view(), name="heatwave-monitoring"),
    path("get-heatwave-detail/", HeatwaveDetailView.as_view(), name="heatwave-detail"),
]
